CREATE DATABASE IF NOT EXISTS mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'passwd';
GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpasswd';
FLUSH PRIVILEGES;

